version: "3.8"
services:
 nginx:
  container_name: nginx
  image: nginx:latest
  ports:
   - target: 80
     published: 80
  volumes:
   - type: bind
     source: ./nginx.conf
     target: /etc/nginx/nginx.conf
 front-end:
  container_name: front-end
  image: jackmqa/front-end:latest
  build: ./front-end
 personal-api:
  container_name: personal-api
  image: jackmqa/personal-api:latest
  build: ./personal-api
  deploy:
   replicas: 3
 player-api:
  container_name: player-api
  image: jackmqa/player-api:latest
  build: ./player-api
  deploy:
   replicas: 3
 stats-api:
  container_name: stats-api
  image: jackmqa/stats-api:latest
  build: ./stats-api
  deploy:
   replicas: 3